// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBaVIVVMVrGrvvy-Y0HSp_duzhrCoq3-VI',
    appId: '1:806726458137:web:3d322049f03811b76fc388',
    messagingSenderId: '806726458137',
    projectId: 'map-bc7de',
    authDomain: 'map-bc7de.firebaseapp.com',
    storageBucket: 'map-bc7de.appspot.com',
    measurementId: 'G-H4HHPF3277',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDlYDrbQ-dVRaVJO_UfECA5sauo4ohex3A',
    appId: '1:806726458137:android:767d081af6514b816fc388',
    messagingSenderId: '806726458137',
    projectId: 'map-bc7de',
    storageBucket: 'map-bc7de.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCk8xOKfXk29YwfMxTRL8vg-mY9z23US3o',
    appId: '1:806726458137:ios:d35a1712a9423e416fc388',
    messagingSenderId: '806726458137',
    projectId: 'map-bc7de',
    storageBucket: 'map-bc7de.appspot.com',
    iosBundleId: 'com.example.googlemapproject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCk8xOKfXk29YwfMxTRL8vg-mY9z23US3o',
    appId: '1:806726458137:ios:d35a1712a9423e416fc388',
    messagingSenderId: '806726458137',
    projectId: 'map-bc7de',
    storageBucket: 'map-bc7de.appspot.com',
    iosBundleId: 'com.example.googlemapproject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBaVIVVMVrGrvvy-Y0HSp_duzhrCoq3-VI',
    appId: '1:806726458137:web:fd9ba8a7614bc7b46fc388',
    messagingSenderId: '806726458137',
    projectId: 'map-bc7de',
    authDomain: 'map-bc7de.firebaseapp.com',
    storageBucket: 'map-bc7de.appspot.com',
    measurementId: 'G-1GKHHPHJ5H',
  );
}
